import { ReactComponent as LogoIcon } from './Logo.svg';
import { ReactComponent as ProfileIcon } from './Profile.svg';
import { ReactComponent as CallIcon } from './Call.svg';
import { ReactComponent as MessageIcon } from './Message.svg';
import { ReactComponent as CalendarIcon } from './Calendar.svg';
import { ReactComponent as LocationIcon } from './Location.svg';
import { ReactComponent as FriendIcon } from './2User.svg';
import { ReactComponent as PasswordIcon } from './Password.svg';
import { ReactComponent as DocumentIcon } from './Document.svg';
import { ReactComponent as TimeIcon } from './TimeCircle.svg';
import { ReactComponent as InfoIcon } from './InfoSquare.svg';
import { ReactComponent as Spacer } from './Spacer.svg';

export const logoIcon = <LogoIcon />;
export const profileIcon = <ProfileIcon className='icon-fill' />;
export const callIcon = <CallIcon className='icon-fill' />;
export const messageIcon = <MessageIcon className='icon-fill' />;
export const calendarIcon = <CalendarIcon />;
export const locationIcon = <LocationIcon />;
export const friendIcon = <FriendIcon className='icon-fill' />;
export const passwordIcon = <PasswordIcon className='icon-fill' />;
export const documentIcon = <DocumentIcon />;
export const timeIcon = <TimeIcon />;
export const infoIcon = <InfoIcon />;
export const spacerIcon = <Spacer />;
