export const LIGHT_THEME = `
  --overlay-transparent: rgba(22, 31, 39, 0.7);
  --html-bg: #e8d4d4;
  --bg-primary: #f5f7fa;
  --bg-secondary: #e4e7eb;
  --bg-tertiary: #cbd2d9;
  --text-primary: #161f27;
  --text-secondary: #1f2b36;
  --text-light: #c4c4c4;
  --highlight-red: #f80908;
  --btn-enabled: #cbd2d9;
  --btn-disabled: #e4e7eb;
  --icon-default: #c4c4c4;
  --icon-active: #2f80ed;
  --icon-disabled: #dadada;
  --white: white;
  --blue: blue;
  --gray: gray;
  --green: green;
  --pink: pink;
`;

export const DARK_THEME = `
  --overlay-transparent: rgba(22, 31, 39, 0.7);
  --html-bg: brown;
  --bg-primary: black;
  --bg-secondary: darkblue;
  --bg-tertiary: greyblue;
  --text-primary: white;
  --text-secondary: grey;
  --text-light: smoke;
  --highlight-red: pink;
  --btn-enabled: lightblue;
  --btn-disabled: green;
  --icon-default: gold;
  --icon-active: yellow;
  --icon-disabled: lightyellow;
  --white: black;
  --blue: lightblue;
  --gray: smoke;
  --green: yellow;
  --pink: red;
`;
